maria_sharapova = """
Maria Yuryevna Sharapova (UK: /ˌʃærəˈpoʊvə/ SHARR-ə-POH-və, US: /ˌʃɑːr-/ SHAR-;[4] Russian: Мари́я Ю́рьевна Шара́пова, IPA: [mɐˈrʲijə ʂɐˈrapəvə] (About this soundlisten); born 19 April 1987) is a Russian former professional tennis player. Although she played under the banner of Russia with the Women's Tennis Association (WTA), she has lived in and been a United States permanent resident since 1994.[5] Sharapova competed on the WTA Tour from 2001 to 2020 and had been ranked world No. 1 in singles by the WTA on five separate occasions, for a total of 21 weeks. She is one of ten women, and the only Russian, to hold the career Grand Slam. She is also an Olympic medalist, having won a silver medal in women's singles at the 2012 Summer Olympics in London. Sharapova achieved a rare level of longevity in tennis, with several tennis pundits and former players calling Sharapova one of tennis' best competitors.[6]

Sharapova became the world No. 1 for the first time on 22 August 2005, at the age of 18, becoming the first Russian female tennis player to top the singles rankings, and last held the ranking for a fifth time for four weeks from 11 June 2012, to 8 July 2012.[7][8] She won five Grand Slam titles — two at the French Open and one each at the Australian Open, Wimbledon, and the US Open, winning 36 titles in total, including the year-ending WTA Finals in her debut in 2004. She also won three doubles titles. She was also considered to be one of the greatest rivals of Serena Williams, who is widely considered to be the greatest female tennis player of all time.

Sharapova has been featured in a number of modeling assignments, including a feature in the Sports Illustrated Swimsuit Issue. She has appeared in many advertisements, including those for Nike, Prince, and Canon, and has been the face of several fashion houses, most notably Cole Haan. Since February 2007, she has been a United Nations Development Programme Goodwill Ambassador, concerned specifically with the Chernobyl Recovery and Development Programme. In June 2011, she was named one of the "30 Legends of Women's Tennis: Past, Present and Future" by Time[9] and in March 2012 was named one of the "100 Greatest of All Time" by Tennis Channel. According to Forbes, she has been named highest-paid female athlete in the world for 11 consecutive years and earned US$285 million (including prize money) since she turned pro in 2001.[10][11] In 2018, she launched a new programme to mentor women entrepreneurs.[12]

In March 2016, Sharapova revealed she had failed a drug test at the 2016 Australian Open. She had tested positive for meldonium, a substance that had been banned (effective January 1, 2016) by the World Anti-Doping Agency (WADA). On 8 June 2016, she was suspended from playing tennis for two years by the International Tennis Federation (ITF).[13][14][15] On 4 October 2016, the suspension was reduced to 15 months, starting from the date of the failed test, as the Court of Arbitration for Sports found that she had committed "no significant fault" and that she had taken the substance "based on a doctor's recommendation… with good faith belief that it was appropriate and compliant with the relevant rules".[16][17][18] She returned to the WTA Tour on 26 April 2017 at the Porsche Tennis Grand Prix.
"""

juan_cuadrado = """
Juan Guillermo Cuadrado Bello (born 26 May 1988) is a Colombian professional footballer who plays for Serie A club Juventus and the Colombia national team.[4] He is known for his direct style of play, including his pace (both on and off the ball) as well as his dribbling skills. He started off in a central midfield role, acting as a defensive midfielder early in his career, also being used as a forward on occasion, before being moved into as a wider positions in which he now usually plays, often operating as a right-sided winger, attacking midfielder, full-back or wing-back.[5]

Having begun his career at Independiente Medellín, Cuadrado moved to Italy in 2009 to join Udinese. Used sparingly at the club, he was loaned to Lecce for the 2011–12 season, where despite relegation from Serie A, his performances earned a transfer to Fiorentina. In February 2015, he was signed by Chelsea, but after playing sparingly, was loaned to Juventus for consecutive seasons, where he won successive Serie A and Coppa Italia titles. He joined the club permanently in 2017, and added a third consecutive domestic double the following season, followed by a two more consecutive league titles and a Supercoppa Italiana over the next two seasons.

Cuadrado made his senior international debut in 2010, and has since earned 100 caps. He was part of the Colombian squads which took part at five editions of the Copa América (2011, 2015, 2016, 2019 and 2021), reaching the quarter-finals on three occasions, and contributing to their third-place finishes in 2016 and 2021; Cuadrado also represented his nation at two editions of the FIFA World Cup, in 2014 and 2018.[6]
"""

kevin_durant = """
Kevin Wayne Durant (/dəˈrænt/; born September 29, 1988), also known simply by his initials KD, is an American professional basketball player for the Brooklyn Nets of the National Basketball Association (NBA). He played one season of college basketball for the University of Texas, and was selected as the second overall pick by the Seattle SuperSonics in the 2007 NBA draft. He played nine seasons with the franchise, which became the Oklahoma City Thunder in 2008, before signing with the Golden State Warriors in 2016, winning back-to-back championships in 2017 and 2018. After sustaining an Achilles injury in the 2019 finals, he joined the Nets as a free agent that summer. He has often been called one of the best active players in the NBA.[1][2][3]

Durant was a heavily recruited high school prospect who was widely regarded as the second-best player in his class. In college, he won numerous year-end awards and became the first freshman to be named Naismith College Player of the Year. As a professional, he has won two NBA championships, an NBA Most Valuable Player Award, two Finals MVP Awards, two NBA All-Star Game Most Valuable Player Awards, four NBA scoring titles, the NBA Rookie of the Year Award, and two Olympic gold medals. Durant has also been selected to nine All-NBA teams and eleven NBA All-Star teams.

Off the court, Durant is one of the highest-earning basketball players in the world, due in part to endorsement deals with companies such as Foot Locker and Nike. He has developed a reputation for philanthropy and regularly leads the league in All-Star votes and jersey sales. In recent years, he has contributed to The Players' Tribune as both a photographer and writer. In 2012, he ventured into acting, appearing in the film Thunderstruck.
"""

eric_clapton = """
Eric Patrick Clapton, CBE (born 30 March 1945) is an English rock and blues guitarist, singer, and songwriter. He is the only three-time inductee to the Rock and Roll Hall of Fame: once as a solo artist and separately as a member of the Yardbirds and of Cream. Clapton has been referred to as one of the most important and influential guitarists of all time.[2] Clapton ranked second in Rolling Stone's list of the "100 Greatest Guitarists of All Time"[3] and fourth in Gibson's "Top 50 Guitarists of All Time".[4] He was also named number five in Time magazine's list of "The 10 Best Electric Guitar Players" in 2009.[5]

After playing in a number of different local bands, Clapton joined the Yardbirds in 1963, replacing founding guitarist Top Topham. Dissatisfied with the change of the Yardbirds sound from blues rock to a more radio-friendly pop rock sound, Clapton left in 1965 to play with John Mayall & the Bluesbreakers, with whom he played on one album. After leaving Mayall in 1966, he formed the power trio Cream with drummer Ginger Baker and bassist Jack Bruce, in which Clapton played sustained blues improvisations and "arty, blues-based psychedelic pop".[6] After Cream broke up in November 1968, he formed blues rock band Blind Faith with Baker, Steve Winwood, and Ric Grech, recording one album and performing on one tour before they broke up, leading Clapton to embark on a solo career in 1970.

Alongside his solo career, he also performed with Delaney & Bonnie and Derek and the Dominos, with whom he recorded "Layla", one of his signature songs. He continued to record a number of successful solo albums and songs over the next several decades, including a 1974 cover of Bob Marley's "I Shot the Sheriff" (which helped reggae reach a mass market),[7] the country-infused Slowhand album (1977) and the pop rock of 1986's August. Following the death of his son Conor in 1991, Clapton's grief was expressed in the song "Tears in Heaven", which appeared on his Unplugged album, and in 1996 he had another top-40 hit with the R&B crossover "Change the World", and in 1998 released the Grammy award-winning "My Father's Eyes". Since 1999, he has recorded a number of traditional blues and blues rock albums and hosted the periodic Crossroads Guitar Festival. His most recent studio album is 2018's Happy Xmas.

Clapton has received 18 Grammy Awards as well as the Brit Award for Outstanding Contribution to Music.[8][9] In 2004 he was awarded a CBE at Buckingham Palace for services to music.[10] He has received four Ivor Novello Awards from the British Academy of Songwriters, Composers and Authors, including the Lifetime Achievement Award. In his solo career, Clapton has sold more than 100 million records worldwide, making him one of the best-selling musicians of all time.[11] In 1998, Clapton, a recovering alcoholic and drug addict, founded the Crossroads Centre on Antigua, a medical facility for recovering substance abusers.[12]
"""

ruben_blades = """
Rubén Blades Bellido de Luna (born July 16, 1948), known professionally as Rubén Blades (Spanish: [ruˈβem ˈblaðes], but [- ˈbledz] in Panama and within the family),[1] is a Panamanian musician, singer, composer, actor, activist, and politician, performing musically most often in the salsa, and Latin jazz genres. As a songwriter, Blades brought the lyrical sophistication of Central American nueva canción and Cuban nueva trova as well as experimental tempos and politically inspired Son Cubano salsa to his music, creating "thinking persons' (salsa) dance music". Blades has written dozens of hit songs, including "Pedro Navaja" and "El Cantante" (which became Héctor Lavoe's signature song). He has won nine Grammy Awards[2] out of seventeen nominations and five Latin Grammy Awards.[3]

His acting career began in 1983, and has continued, sometimes with several-year breaks to focus on other projects. He has prominent roles in films such as Crossover Dreams (1985), The Milagro Beanfield War (1988), The Super (1991), Predator 2 (1990), Color of Night (1994), Safe House (2012), The Counselor (2013) and Hands of Stone (2016), along with three Emmy Award nominations for his performances in The Josephine Baker Story (1991), Crazy from the Heart (1992) and The Maldonado Miracle (2003). He portrayed Daniel Salazar, a main character on the TV series Fear the Walking Dead (2015–2017; 2019–present).

He is an icon in Panama and is much admired throughout Latin America and Spain, and managed to attract 17% of the vote in his failed attempt to win the Panamanian presidency in 1994. In September 2004, he was appointed minister of tourism by Panamanian president Martín Torrijos for a five-year term. He holds a Bachelor of Arts' Law degree from the University of Panama and an LL.M in International Law from Harvard University.[1] He is married to singer Luba Mason.[4]
"""

amy_winehouse = """
Amy Jade Winehouse (14 September 1983 – 23 July 2011) was an English singer and songwriter known for her deep, expressive contralto vocals and her eclectic mix of musical genres, including soul, rhythm and blues and jazz.

A member of the National Youth Jazz Orchestra during her youth, Winehouse signed to Simon Fuller's 19 Management in 2002 and soon recorded a number of songs before signing a publishing deal with EMI. She also formed a working relationship with producer Salaam Remi through these record publishers. Winehouse's debut album, Frank, was released in 2003. Many of the album's songs were influenced by jazz and, apart from two covers, were co-written by Winehouse. Frank was a critical success in the UK and was nominated for the Mercury Prize. The song "Stronger Than Me" won her the Ivor Novello Award for Best Contemporary Song from the British Academy of Songwriters, Composers, and Authors.

Winehouse released her follow-up album, Back to Black, in 2006, which went on to become an international success and one of the best-selling albums in UK history.[1] At the 2007 Brit Awards it was nominated for British Album of the Year, and she received the award for British Female Solo Artist. The song "Rehab" won her a second Ivor Novello Award. At the 50th Grammy Awards in 2008, she won five awards, tying the then record for the most wins by a female artist in a single night and becoming the first British woman to win five Grammys, including three of the General Field "Big Four" Grammy Awards: Best New Artist, Record of the Year and Song of the Year (for "Rehab"), as well as Best Pop Vocal Album.

Winehouse was plagued by drug and alcohol addiction. She died of alcohol poisoning on 23 July 2011, at the age of 27. After her death, Back to Black temporarily became the UK's best-selling album of the 21st century.[2] VH1 ranked Winehouse 26th on their list of the 100 Greatest Women in Music.
"""
